stages:
  - deploy

########################## DEPLOYMENT ##############################

.deploy_base:
  image: kroniak/ssh-client
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa

.deploy_premium:
  extends: .deploy_base
  only:
    - premium 

.deploy_production:
  extends: .deploy_base
  only:
    - master

deploy to premium:
  stage: deploy
  extends: .deploy_premium
  script:
    - ssh rnet@10.12.0.60 "cd RNet && git pull origin develop && npm install && npm link @rnet.cf/modules"

deploy to dev:
  stage: deploy
  extends: .deploy_base
  script:
    - ssh rnet@10.12.0.95 "cd RNet && git pull origin develop && npm install && npm link @rnet.cf/modules && pm2 restart RNet"
  only: 
    - develop
